DROP TABLE productos CASCADE CONSTRAINTS;
DROP TABLE precios_productos CASCADE CONSTRAINTS;


CREATE TABLE PRODUCTOS (
    CO_PRODUCTO NUMBER
    GENERATED ALWAYS AS IDENTITY 
                        MINVALUE 1 
                        MAXVALUE 99
                        INCREMENT BY 1 
                        START WITH 1  
                        NOORDER  
                        NOCYCLE  NOT NULL ENABLE,
    NO_PRODUCTO VARCHAR(100),
    CONSTRAINT co_producto_prod_pk PRIMARY KEY(CO_PRODUCTO)
);

CREATE TABLE PRECIOS_PRODUCTOS (
    CO_PRODUCTO NUMBER,
    PRECIO NUMBER,
    FECHA_ACTUALIZACION DATE,
    CONSTRAINT co_producto_pp_fk FOREIGN KEY(CO_PRODUCTO) REFERENCES PRODUCTOS(CO_PRODUCTO)
);

/* CREAMOS EL TRIGGER */

CREATE OR REPLACE TRIGGER trigger_productos
AFTER INSERT ON PRODUCTOS
FOR EACH ROW
BEGIN
    INSERT INTO PRECIOS_PRODUCTOS (CO_PRODUCTO, PRECIO, FECHA_ACTUALIZACION)
    VALUES(:NEW.CO_PRODUCTO, 100, SYSDATE);
END;

/* INSERTO DATOS */

INSERT INTO PRODUCTOS (no_producto) VALUES('Pantalon');
INSERT INTO PRODUCTOS (no_producto) VALUES('Zapatos');
INSERT INTO PRODUCTOS (no_producto) VALUES('Comida');

/* PROBAMOS EL TRIGGER */

SELECT * from productos;
SELECT * from precios_productos;